# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 15 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: otx_feed
      run: |
        python ./otx_feed.py
      env:
        OTXKEY: ${{ secrets.OTXKEY }}
        MAIL_NOTICE: ${{ secrets.MAI_NOTICE }}
        MAILBOXRECV: ${{ secrets.MAILBOXRECV }}
        MAILBOXSEND: ${{ secrets.MAILBOXSEND }}
        MAILPWSEND: ${{ secrets.MAILPWSEND }}
